version: "3.8"

volumes:
  database_data:
    driver: local

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3308:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
      - ./mariadb:/opt/data
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Bangkok

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "9999:80"
    environment:
      PMA_HOST: mariadb
